### ISSUE TITLE
clfreport :: produce predictions from a pickled estimator

### ISSUE THREAD

**Issue by Aylr** [HealthCatalyst/healthcareai-py#153]
## Ideas

- This may be a general predictor that can use either a fresh estimator or one from a pickle file.

## Subtasks

- [x] create clean prediction methods
- [x] test what should be tested
- [x] move db validation to separate file
- [x] wire predictions up the chain to advanced
- [x] wire predictions up the chain to simple
   - [x] convert dataframe to numpy array (is this needed?)
   - [x] run dataframe through the pipeline so that the columns are ready to go
   - [x] drop the target column
   - [x] once this works, you've completed the bare bones chain.
       - [ ] assess whether the entire Deploy class is needed at all! Maybe the functions can be torn out to make the toolbox then rebuilt into a simple class interface
- [ ] create example simple and advanced example file

### Transformer Conversions

Work from #212 is being done in this branch due to it's coupled need.
