### ISSUE TITLE
GenerateAUC :: refactor

### ISSUE THREAD

**Issue by Aylr** [HealthCatalyst/healthcareai-py#166]
## TODO

- [x] Consider putting all roc/pr metrics in `TSM.metrics`
- [x] tear apart generate_auc
- [x] remove plot portions of roc/pr
- [x] extract cutoff lists from roc and pr plotters
- [x] create a pr plotter like the existing roc plotter that is wired up to TSM
- [x] wire up new pr plotter to TSM
- [x] wire up a cutoff list to TSM for pr
- [x] wire up a cutoff list to TSM for roc
- [x] fix all the tests you just destroyed
- [x] update docs
