### ISSUE TITLE
Release 1.0!

### ISSUE THREAD

**Issue by Aylr** [HealthCatalyst/healthcareai-py#274]
- [x] tidy up all the broken tests #327 
- [x] submit to pypi
- [ ] submit to anaconda
- [x] do all the release things
- [x] update the changelog #323 
- [x] write up a blog post? #271

**Comment by Aylr** [comment]
Conda support dropped for now. We need to remove a few 3.5 specific things and re-release on conda at a later point.
