### ISSUE TITLE
- example is broken using build_mssql_engine_using_trusted_connections

### ISSUE THREAD

**Issue by Aylr** [HealthCatalyst/healthcareai-py#354]
## STR
- [ ] ucomment the mssql bits in `example_classification_1.py`
- [ ] run the example
- [ ] note the output (function names changed)

## TODO

- [x] audit all example files, commented out code escaped the IDE notice
